/**
 * Seed script - Chemistry questions for the exam platform.
 * Run: node seed.js
 */
const db = require('./database');

// Clear existing questions
db.prepare('DELETE FROM questions').run();
db.prepare('DELETE FROM exam_answers').run();
db.prepare('DELETE FROM exam_sessions').run();

const insertQ = db.prepare(`
  INSERT INTO questions (category, question_text, option_a, option_b, option_c, option_d, correct_answer)
  VALUES (?, ?, ?, ?, ?, ?, ?)
`);

// Shuffle answer options once during seed
function shuffleAndInsert(category, questions) {
  for (const q of questions) {
    const options = [
      { letter: 'A', text: q[1] },
      { letter: 'B', text: q[2] },
      { letter: 'C', text: q[3] },
      { letter: 'D', text: q[4] }
    ];
    // Fisher-Yates shuffle
    for (let i = options.length - 1; i > 0; i--) {
      const j = Math.floor(Math.random() * (i + 1));
      [options[i], options[j]] = [options[j], options[i]];
    }
    const newLetters = ['A', 'B', 'C', 'D'];
    let newCorrect = 'A';
    options.forEach((opt, idx) => {
      if (opt.letter === q[5]) newCorrect = newLetters[idx];
    });
    insertQ.run(category, q[0], options[0].text, options[1].text, options[2].text, options[3].text, newCorrect);
  }
}

const chemistryQuestions = [
  // SET 1 — Atomic Structure & Periodic Table
  ["Which subatomic particle determines the atomic number of an element?", "Neutron", "Proton", "Electron", "Positron", "B"],
  ["Which particles are located in the nucleus of an atom?", "Electrons only", "Protons and electrons", "Protons and neutrons", "Neutrons and electrons", "C"],
  ["The mass number of an atom is equal to:", "Protons only", "Neutrons only", "Protons + electrons", "Protons + neutrons", "D"],
  ["Which quantum number determines the shape of an orbital?", "Principal quantum number (n)", "Azimuthal quantum number (l)", "Magnetic quantum number (m)", "Spin quantum number (s)", "B"],
  ["What is the correct electron configuration for oxygen (Z = 8)?", "1s² 2s¹ 2p⁵", "1s¹ 2s² 2p⁵", "1s² 2s² 2p⁶", "1s² 2s² 2p⁴", "D"],
  ["Elements in the same group of the periodic table have:", "The same number of neutrons", "Similar chemical properties", "The same mass number", "The same atomic radius", "B"],
  ["Which of the following is a metalloid?", "Chlorine", "Sodium", "Silicon", "Argon", "C"],
  ["Ionization energy is defined as the energy required to:", "Break a covalent bond", "Remove an electron from a gaseous atom", "Add an electron to a gaseous atom", "Break an ionic bond", "B"],
  ["Which element has the highest electronegativity?", "Oxygen", "Fluorine", "Nitrogen", "Chlorine", "B"],
  ["Electron affinity refers to the energy change when:", "An atom loses an electron", "An atom gains an electron", "A bond is broken", "A nucleus emits radiation", "B"],
  ["Isotopes of an element differ in the number of:", "Protons", "Electrons", "Neutrons", "Orbitals", "C"],
  ["Which orbital type can hold a maximum of 10 electrons?", "s", "p", "d", "f", "C"],
  ["In which period is potassium (K) located?", "Period 1", "Period 2", "Period 3", "Period 4", "D"],
  ["Which property increases across a period from left to right?", "Atomic radius", "Metallic character", "Electronegativity", "Ionic radius", "C"],
  ["Which of the following is a noble gas?", "Fluorine", "Nitrogen", "Neon", "Boron", "C"],

  // SET 2 — Chemical Bonds
  ["Which type of bond involves the sharing of electron pairs between atoms?", "Ionic bond", "Metallic bond", "Covalent bond", "Hydrogen bond", "C"],
  ["Which bond is formed by the transfer of electrons from one atom to another?", "Ionic bond", "Covalent bond", "Metallic bond", "Coordinate covalent bond", "A"],
  ["A coordinate covalent bond is formed when:", "Each atom donates one electron", "One atom donates both electrons", "Electrons are transferred", "Electrons move freely", "B"],
  ["Metallic bonding is best described as:", "Sharing of electron pairs", "Transfer of electrons", "Attraction between metal cations and delocalized electrons", "Attraction between dipoles", "C"],
  ["Which of the following is the weakest type of bond?", "Ionic bond", "Covalent bond", "Metallic bond", "Hydrogen bond", "D"],
  ["A polar covalent bond forms when:", "Electrons are shared unequally", "Electrons are shared equally", "Electrons are transferred", "Electrons are delocalized", "A"],
  ["Which molecule contains a nonpolar covalent bond?", "HCl", "HF", "O₂", "H₂O", "C"],
  ["Which molecule contains a polar covalent bond?", "N₂", "Cl₂", "CO", "O₂", "C"],
  ["What causes ionic compounds to have high melting points?", "Weak intermolecular forces", "Strong electrostatic attraction", "Free-moving electrons", "Hydrogen bonding", "B"],
  ["Hydrogen bonding occurs between molecules containing hydrogen and:", "Any nonmetal", "Highly electronegative atoms (N, O, F)", "Metals", "Noble gases", "B"],
  ["Which of the following is an example of a coordinate covalent bond?", "H–H", "O=O", "NH₄⁺", "NaCl", "C"],
  ["Which type of bond is responsible for the properties of metals such as conductivity?", "Ionic", "Covalent", "Metallic", "Hydrogen", "C"],
  ["Which compound contains an ionic bond?", "CO₂", "H₂O", "NaCl", "CH₄", "C"],
  ["A molecule with a symmetrical distribution of charge is:", "Polar", "Nonpolar", "Ionic", "Metallic", "B"],
  ["Which force is responsible for holding water molecules together?", "Ionic attraction", "Metallic bonding", "Hydrogen bonding", "Covalent bonding only", "C"],

  // SET 3 — Energy Changes in Chemical Reactions
  ["Enthalpy (ΔH) is defined as:", "Heat content of a system at constant pressure", "Disorder of a system", "Energy required to break bonds", "Energy of motion", "A"],
  ["An exothermic reaction is one that:", "Absorbs heat", "Releases heat", "Has no heat change", "Requires light", "B"],
  ["An endothermic reaction is characterized by:", "Heat release", "Heat absorption", "No temperature change", "Gas formation", "B"],
  ["Entropy (ΔS) is a measure of:", "Heat content", "Disorder or randomness", "Reaction rate", "Bond strength", "B"],
  ["Gibbs free energy (ΔG) determines:", "Reaction speed", "Whether a reaction is spontaneous", "Reaction color", "Reaction mechanism", "B"],
  ["A reaction is spontaneous when:", "ΔG > 0", "ΔG = 0", "ΔG < 0", "ΔH = 0", "C"],
  ["Combustion reactions are generally:", "Endothermic", "Exothermic", "Neutral", "Non‑energetic", "B"],
  ["Thermal decomposition reactions are usually:", "Exothermic", "Endothermic", "Spontaneous", "Redox reactions", "B"],
  ["Which of the following increases the entropy of a system?", "Gas → solid", "Liquid → solid", "Solid → gas", "Gas → liquid", "C"],
  ["A reaction with ΔH < 0 and ΔS > 0 is:", "Always spontaneous", "Never spontaneous", "Spontaneous only at high temperatures", "Spontaneous only at low temperatures", "A"],
  ["A reaction with ΔH > 0 and ΔS < 0 is:", "Always spontaneous", "Never spontaneous", "Spontaneous at high temperature", "Spontaneous at low temperature", "B"],
  ["The unit of enthalpy change is:", "Joule (J)", "Pascal (Pa)", "Watt (W)", "Coulomb (C)", "A"],
  ["Which statement is true for exothermic reactions?", "Products have higher energy than reactants", "Reactants have higher energy than products", "Energy is absorbed", "Entropy always decreases", "B"],
  ["In an endothermic reaction, the temperature of the surroundings:", "Increases", "Decreases", "Remains constant", "Becomes unstable", "B"],
  ["A reaction with ΔG = 0 is:", "At equilibrium", "Spontaneous", "Non‑spontaneous", "Impossible", "A"],

  // SET 4 — Chemical Kinetics & Chemical Equilibrium
  ["The rate of a chemical reaction is defined as:", "Change in concentration per unit time", "Heat released per unit time", "Number of collisions per second", "Change in temperature per unit time", "A"],
  ["Which factor does not affect reaction rate?", "Temperature", "Catalyst", "Concentration", "Color of reactants", "D"],
  ["Increasing temperature generally:", "Decreases reaction rate", "Increases reaction rate", "Has no effect", "Stops the reaction", "B"],
  ["A catalyst increases reaction rate by:", "Increasing activation energy", "Decreasing activation energy", "Increasing product concentration", "Increasing entropy", "B"],
  ["The minimum energy required for a reaction to occur is called:", "Enthalpy", "Entropy", "Activation energy", "Free energy", "C"],
  ["Chemical equilibrium is reached when:", "Reactants are fully consumed", "Forward and reverse rates are equal", "Products stop forming", "Temperature becomes constant", "B"],
  ["At equilibrium, the concentrations of reactants and products:", "Are equal", "Are constant", "Become zero", "Continuously increase", "B"],
  ["The equilibrium constant (K) depends on:", "Temperature", "Pressure only", "Catalyst", "Reaction rate", "A"],
  ["If K >> 1, the reaction favors:", "Reactants", "Products", "Neither", "Both equally", "B"],
  ["According to Le Chatelier's principle, increasing pressure shifts equilibrium toward:", "The side with more gas moles", "The side with fewer gas moles", "Solids", "Liquids", "B"],
  ["Adding more reactant to a system at equilibrium will:", "Shift equilibrium to the right", "Shift equilibrium to the left", "Have no effect", "Stop the reaction", "A"],
  ["Increasing temperature in an exothermic reaction shifts equilibrium:", "To the right", "To the left", "No change", "Toward solids", "B"],
  ["A catalyst affects equilibrium by:", "Shifting it to the right", "Shifting it to the left", "Changing K", "Reaching equilibrium faster", "D"],
  ["If Q < K, the reaction will proceed:", "Forward", "Backward", "Not at all", "At equilibrium", "A"],
  ["If Q > K, the reaction will shift:", "Toward products", "Toward reactants", "Not shift", "Toward solids", "B"],
  // SET 5 — Solutions
  ["A suspension is best described as:", "A homogeneous mixture", "A heterogeneous mixture with large particles", "A solution of ions", "A colloid", "B"],
  ["A colloidal solution has particle sizes:", "Larger than 1 µm", "Smaller than 1 nm", "Between 1 nm and 1000 nm", "Exactly 1 mm", "C"],
  ["Which of the following is a true solution?", "Milk", "Fog", "Sugar dissolved in water", "Blood", "C"],
  ["Solubility is defined as:", "The ability of a solute to evaporate", "The maximum amount of solute that can dissolve in a solvent", "The speed of dissolution", "The density of a solvent", "B"],
  ["The unit for molarity (M) is:", "mol/kg", "mol/L", "g/L", "g/mol", "B"],
  ["Molality (m) is defined as:", "Moles of solute per liter of solution", "Moles of solute per kilogram of solvent", "Grams of solute per liter", "Grams of solvent per mole", "B"],
  ["Avogadro's number is equal to:", "6.02 × 10¹⁹", "6.02 × 10²³", "3.14 × 10²³", "1.00 × 10⁶", "B"],
  ["The mass percent concentration is defined as:", "(mass of solute / mass of solution) × 100", "(mass of solvent / mass of solute) × 100", "(volume of solute / volume of solvent) × 100", "(moles of solute / moles of solvent) × 100", "A"],
  ["A solution with a high amount of solute compared to solvent is called:", "Dilute", "Concentrated", "Saturated", "Unsaturated", "B"],
  ["A saturated solution contains:", "No solute", "Less solute than it can dissolve", "The maximum amount of dissolved solute", "Only solvent", "C"],
  ["A supersaturated solution is:", "A solution at equilibrium", "A solution containing more solute than normally possible", "A dilute solution", "A colloid", "B"],
  ["The density of a solution is expressed in:", "mol/L", "g/mL", "g/mol", "mol/kg", "B"],
  ["Increasing temperature generally:", "Decreases solubility of solids", "Increases solubility of solids", "Has no effect on solubility", "Makes all solutes insoluble", "B"],
  ["The concentration unit g/L expresses:", "Mass concentration", "Molarity", "Molality", "Density", "A"],
  ["Which of the following is a colloid?", "Salt water", "Smoke", "Copper wire", "Oxygen gas", "B"],

  // SET 6 — Electrolyte Solutions
  ["An electrolyte is a substance that:", "Does not dissolve in water", "Produces ions in solution", "Produces only molecules in solution", "Cannot conduct electricity", "B"],
  ["Strong electrolytes are substances that:", "Partially dissociate in water", "Do not dissociate at all", "Completely dissociate into ions", "Dissolve only in organic solvents", "C"],
  ["Weak electrolytes are characterized by:", "Complete ionization", "Partial ionization", "No ionization", "Metallic bonding", "B"],
  ["The degree of dissociation (α) represents:", "The number of moles of solvent", "The fraction of molecules that ionize", "The mass of solute", "The boiling point of the solution", "B"],
  ["A high degree of dissociation indicates:", "A weak electrolyte", "A strong electrolyte", "A non‑electrolyte", "A colloid", "B"],
  ["The dissociation constant (Ka or Kb) measures:", "Solubility", "Strength of an electrolyte", "Reaction rate", "Density of a solution", "B"],
  ["Which of the following is a strong electrolyte?", "CH₃COOH", "NH₃", "NaCl", "H₂O", "C"],
  ["Which of the following is a weak electrolyte?", "HCl", "NaOH", "KBr", "HF", "D"],
  ["A non‑electrolyte is a substance that:", "Produces many ions", "Produces few ions", "Produces no ions", "Conducts electricity strongly", "C"],
  ["Ionic reactions occur mainly in:", "Solid metals", "Nonpolar solvents", "Aqueous solutions", "Gases", "C"],
  ["Which of the following is NOT an electrolyte?", "Glucose", "HCl", "NaOH", "KNO₃", "A"],
  ["Conductivity of an electrolyte solution increases with:", "Decreasing ion concentration", "Increasing ion concentration", "Removing ions", "Adding non‑electrolytes", "B"],
  ["A strong acid in water behaves as:", "A non‑electrolyte", "A weak electrolyte", "A strong electrolyte", "A colloid", "C"],
  ["Which solution will conduct electricity best?", "Sugar solution", "Distilled water", "NaCl solution", "Alcohol solution", "C"],
  ["The ions produced by the dissociation of NaCl in water are:", "Na and Cl", "Na⁺ and Cl⁻", "Na²⁺ and Cl²⁻", "Na⁻ and Cl⁺", "B"],
  // SET 7 — Acids, Bases, and Salts
  ["According to Arrhenius, an acid is a substance that:", "Produces OH⁻ in water", "Produces H⁺ in water", "Accepts a proton", "Donates an electron pair", "B"],
  ["According to Arrhenius, a base is a substance that:", "Produces H⁺ in water", "Produces OH⁻ in water", "Donates a proton", "Accepts an electron pair", "B"],
  ["According to Brønsted–Lowry, an acid is a:", "Proton donor", "Proton acceptor", "Electron donor", "Electron pair acceptor", "A"],
  ["According to Brønsted–Lowry, a base is a:", "Proton donor", "Proton acceptor", "Electron donor", "Electron pair acceptor", "B"],
  ["According to Lewis, a base is a substance that:", "Donates a proton", "Accepts a proton", "Donates an electron pair", "Accepts an electron pair", "C"],
  ["A strong acid is one that:", "Partially ionizes", "Completely ionizes", "Does not ionize", "Forms precipitates", "B"],
  ["A weak acid is one that:", "Completely ionizes", "Partially ionizes", "Does not dissolve", "Forms salts only", "B"],
  ["Which of the following is a strong base?", "NH₃", "NaOH", "H₂O", "CH₃COOH", "B"],
  ["Amphoteric substances can:", "Act only as acids", "Act only as bases", "Act as both acids and bases", "Never ionize", "C"],
  ["Which of the following is an amphoteric substance?", "HCl", "NaOH", "H₂O", "CH₄", "C"],
  ["A salt is formed when:", "An acid reacts with a base", "A metal reacts with a metal", "A gas reacts with a solid", "A base reacts with a base", "A"],
  ["Neutralization is the reaction between:", "Acid and metal", "Base and salt", "Acid and base", "Salt and water", "C"],
  ["Hydrolysis of a salt occurs when:", "The salt reacts with water", "The salt decomposes by heat", "The salt reacts with oxygen", "The salt reacts with a metal", "A"],
  ["A salt formed from a strong acid and strong base produces a solution that is:", "Acidic", "Basic", "Neutral", "Amphoteric", "C"],
  ["A salt formed from a weak acid and strong base produces a solution that is:", "Acidic", "Basic", "Neutral", "Amphoteric", "B"],

  // SET 8 — Ionic Product of Water, pH and pOH
  ["The ionic product of water (Kw) at 25°C is:", "1 × 10⁻¹⁰", "1 × 10⁻¹⁴", "1 × 10⁻⁷", "1 × 10⁻²", "B"],
  ["In pure water at 25°C, the concentration of H⁺ is:", "1 × 10⁻¹", "1 × 10⁻⁷", "1 × 10⁻¹⁴", "1 × 10⁻³", "B"],
  ["pH is defined as:", "–log[OH⁻]", "–log[H⁺]", "log[H⁺]", "log[OH⁻]", "B"],
  ["A solution with pH = 2 is:", "Neutral", "Weakly acidic", "Strongly acidic", "Basic", "C"],
  ["A solution with pH = 9 is:", "Strongly acidic", "Weakly acidic", "Neutral", "Basic", "D"],
  ["pOH is defined as:", "–log[H⁺]", "–log[OH⁻]", "log[H⁺]", "log[OH⁻]", "B"],
  ["For any aqueous solution at 25°C, pH + pOH =", "7", "10", "12", "14", "D"],
  ["If [H⁺] = 1 × 10⁻³ M, the pH is:", "2", "3", "4", "5", "B"],
  ["If [OH⁻] = 1 × 10⁻⁴ M, the pOH is:", "2", "3", "4", "5", "C"],
  ["A neutral solution at 25°C has:", "pH = 5", "pH = 7", "pH = 9", "pH = 14", "B"],
  ["If pH = 5, the solution is:", "Basic", "Neutral", "Acidic", "Amphoteric", "C"],
  ["Increasing the concentration of H⁺ ions will:", "Increase pH", "Decrease pH", "Not affect pH", "Make the solution neutral", "B"],
  ["A solution with [H⁺] = 1 × 10⁻⁷ M is:", "Acidic", "Basic", "Neutral", "Amphoteric", "C"],
  ["If pOH = 2, the pH is:", "2", "7", "9", "12", "D"],
  ["A solution with pH = 13 has:", "High [H⁺]", "Low [OH⁻]", "High [OH⁻]", "Equal [H⁺] and [OH⁻]", "C"],
  // SET 9 — Buffers
  ["A buffer solution is a solution that:", "Changes pH easily", "Resists changes in pH", "Has pH = 7", "Contains only salts", "B"],
  ["A buffer is typically made of:", "Strong acid + strong base", "Weak acid + its conjugate base", "Strong acid + strong base salt", "Water + salt", "B"],
  ["Which of the following is a common buffer system?", "HCl + NaCl", "CH₃COOH + CH₃COONa", "NaOH + NaCl", "H₂SO₄ + Na₂SO₄", "B"],
  ["The pH of a buffer solution depends on:", "Temperature only", "The ratio of acid to conjugate base", "The color of the solution", "The boiling point", "B"],
  ["The Henderson–Hasselbalch equation is used to calculate:", "Solubility", "pH of a buffer", "Reaction rate", "Ionic strength", "B"],
  ["A buffer is most effective when:", "pH = pKa", "pH = 14", "pH = 1", "pH = 7", "A"],
  ["Adding a small amount of acid to a buffer will:", "Greatly decrease pH", "Slightly decrease pH", "Not change pH at all", "Greatly increase pH", "B"],
  ["Adding a small amount of base to a buffer will:", "Greatly increase pH", "Slightly increase pH", "Not change pH at all", "Greatly decrease pH", "B"],
  ["Which of the following is a physiological buffer?", "NaCl", "H₂CO₃/HCO₃⁻", "HCl", "NH₄Cl", "B"],
  ["The main buffer system in human blood is:", "Phosphate buffer", "Carbonate buffer", "Bicarbonate buffer", "Ammonia buffer", "C"],
  ["A buffer made of NH₃ and NH₄Cl is a:", "Strong acid buffer", "Weak base buffer", "Strong base buffer", "Neutral buffer", "B"],
  ["A buffer resists pH change because it contains:", "Only strong acids", "Only strong bases", "A weak acid/base pair", "No ions", "C"],
  ["When a buffer is diluted with water, its pH:", "Increases", "Decreases", "Remains nearly constant", "Becomes zero", "C"],
  ["The capacity of a buffer increases when:", "Concentration of components increases", "Temperature decreases", "Water is added", "Salt is removed", "A"],
  ["A buffer works best when the concentrations of acid and conjugate base are:", "Very different", "Equal", "Zero", "Extremely low", "B"],

  // SET 10 — Colligative Properties & Colloids
  ["Colligative properties depend on:", "The identity of the solute", "The color of the solute", "The number of solute particles", "The mass of the solvent", "C"],
  ["Which of the following is a colligative property?", "Density", "Boiling point elevation", "Color change", "Viscosity", "B"],
  ["Adding a solute to a solvent will:", "Increase the freezing point", "Decrease the freezing point", "Not affect the freezing point", "Turn the solution into a gas", "B"],
  ["Boiling point elevation occurs because:", "Vapor pressure increases", "Vapor pressure decreases", "Solvent evaporates faster", "Solute reacts with solvent", "B"],
  ["Osmotic pressure is defined as:", "Pressure required to stop osmosis", "Pressure that increases boiling point", "Pressure that lowers freezing point", "Pressure caused by gases", "A"],
  ["A solution with more dissolved particles will have:", "Lower osmotic pressure", "Higher osmotic pressure", "No osmotic pressure", "Constant osmotic pressure", "B"],
  ["Which solution has the highest boiling point?", "Pure water", "0.1 M NaCl", "0.1 M glucose", "0.2 M NaCl", "D"],
  ["The Tyndall effect is used to distinguish:", "Solutions from gases", "Colloids from true solutions", "Solids from liquids", "Metals from nonmetals", "B"],
  ["The Tyndall effect is caused by:", "Absorption of light", "Scattering of light", "Reflection of light", "Refraction of light", "B"],
  ["Which of the following is a colloid?", "Salt water", "Sugar solution", "Milk", "Oxygen gas", "C"],
  ["Colloidal particles are typically:", "Larger than 1 mm", "Smaller than 1 nm", "Between 1 nm and 1000 nm", "Exactly 1 cm", "C"],
  ["Lowering of vapor pressure occurs when:", "Solute is added", "Solvent is removed", "Temperature decreases", "Pressure increases", "A"],
  ["Freezing point depression is proportional to:", "Solute identity", "Solvent color", "Number of solute particles", "Temperature", "C"],
  ["Which of the following is NOT a colligative property?", "Osmotic pressure", "Boiling point elevation", "Freezing point depression", "Electrical conductivity", "D"],
  ["Colloids are stable because:", "Particles settle quickly", "Particles repel each other", "Particles dissolve completely", "Particles are too large to scatter light", "B"],
  // SET 11 — Oxidation–Reduction (Redox)
  ["Oxidation is defined as:", "Gain of electrons", "Loss of electrons", "Gain of protons", "Loss of neutrons", "B"],
  ["Reduction is defined as:", "Gain of electrons", "Loss of electrons", "Gain of protons", "Loss of protons", "A"],
  ["In a redox reaction, the oxidizing agent is the species that:", "Is oxidized", "Gains electrons", "Loses electrons", "Decreases oxidation number", "B"],
  ["The reducing agent is the species that:", "Gains electrons", "Is reduced", "Loses electrons", "Increases oxidation number", "C"],
  ["The oxidation number of oxygen in most compounds is:", "+2", "–1", "–2", "0", "C"],
  ["The oxidation number of hydrogen in most compounds is:", "–1", "0", "+1", "+2", "C"],
  ["In the compound KMnO₄, the oxidation number of Mn is:", "+2", "+4", "+6", "+7", "D"],
  ["Which of the following is a redox reaction?", "HCl + NaOH → NaCl + H₂O", "AgNO₃ + NaCl → AgCl + NaNO₃", "2Mg + O₂ → 2MgO", "BaCl₂ + H₂SO₄ → BaSO₄ + 2HCl", "C"],
  ["In the reaction: Zn → Zn²⁺ + 2e⁻, zinc is:", "Reduced", "Oxidized", "Neutralized", "Hydrolyzed", "B"],
  ["In the reaction: Cl₂ + 2e⁻ → 2Cl⁻, chlorine is:", "Oxidized", "Reduced", "Neutral", "Decomposed", "B"],
  ["A species that causes oxidation of another species is called:", "Reducing agent", "Oxidizing agent", "Catalyst", "Base", "B"],
  ["The oxidation number of an element in its elemental form is always:", "+1", "–1", "0", "+2", "C"],
  ["In H₂O₂, the oxidation number of oxygen is:", "–2", "–1", "0", "+1", "B"],
  ["The galvanic series ranks metals according to their:", "Atomic mass", "Reactivity", "Density", "Melting point", "B"],
  ["In a redox equation, electrons must be:", "Added randomly", "Balanced on both sides", "Ignored", "Doubled", "B"],

  // SET 12 — Electrochemistry
  ["Oxidation always occurs at the:", "Cathode", "Anode", "Salt bridge", "Electrolyte", "B"],
  ["Reduction always occurs at the:", "Anode", "Cathode", "Salt bridge", "Electrode with positive charge in galvanic cells", "B"],
  ["In a galvanic (voltaic) cell, the anode is:", "Positive", "Negative", "Neutral", "Variable", "B"],
  ["In an electrolytic cell, the anode is:", "Positive", "Negative", "Neutral", "Grounded", "A"],
  ["The purpose of the salt bridge in a galvanic cell is to:", "Produce electrons", "Maintain electrical neutrality", "Increase voltage", "Store ions", "B"],
  ["Standard electrode potentials are measured under:", "1 atm, 1 M, 25°C", "2 atm, 2 M, 50°C", "0 atm, 0 M, 0°C", "Any conditions", "A"],
  ["A positive standard cell potential (E°cell) indicates:", "A non‑spontaneous reaction", "A spontaneous reaction", "No reaction", "A neutral reaction", "B"],
  ["In electrolysis, electrical energy is used to:", "Produce heat", "Drive a non‑spontaneous reaction", "Increase entropy", "Lower activation energy", "B"],
  ["Which of the following is produced during the electrolysis of molten NaCl?", "Na⁺ at the anode", "Cl₂ at the anode", "Na metal at the anode", "H₂ gas at the anode", "B"],
  ["During electrolysis of water, hydrogen gas is produced at the:", "Anode", "Cathode", "Salt bridge", "Electrolyte surface", "B"],
  ["The unit of electric charge is the:", "Volt", "Ampere", "Coulomb", "Ohm", "C"],
  ["Faraday's first law of electrolysis states that the mass of substance deposited is proportional to:", "Voltage", "Current × time", "Temperature", "Pressure", "B"],
  ["A galvanic cell converts:", "Electrical energy into chemical energy", "Chemical energy into electrical energy", "Heat into chemical energy", "Light into electrical energy", "B"],
  ["Electroplating is an application of:", "Galvanic cells", "Electrolytic cells", "Nuclear cells", "Fuel cells", "B"],
  ["The standard hydrogen electrode (SHE) has an assigned potential of:", "+1.00 V", "–1.00 V", "0.00 V", "+0.50 V", "C"],
  // SET 13 — Types of Inorganic Compounds
  ["Acidic oxides are typically formed by:", "Metals", "Nonmetals", "Noble gases", "Alkali metals", "B"],
  ["Basic oxides are usually formed by:", "Nonmetals", "Noble gases", "Metals", "Halogens", "C"],
  ["Amphoteric oxides react with:", "Acids only", "Bases only", "Both acids and bases", "Neither acids nor bases", "C"],
  ["Which of the following is an amphoteric oxide?", "CO₂", "Na₂O", "Al₂O₃", "SO₃", "C"],
  ["Acidic oxides are also known as:", "Basic anhydrides", "Acid anhydrides", "Neutral oxides", "Metallic oxides", "B"],
  ["Which of the following is a basic oxide?", "MgO", "CO", "SO₂", "N₂O", "A"],
  ["Neutral oxides include:", "CO₂", "SO₃", "CO", "CaO", "C"],
  ["Hydrides formed between hydrogen and metals are called:", "Covalent hydrides", "Metallic hydrides", "Ionic hydrides", "Complex hydrides", "C"],
  ["Which of the following is a covalent hydride?", "NaH", "CaH₂", "CH₄", "KH", "C"],
  ["Which oxide is acidic?", "CaO", "SO₃", "MgO", "FeO", "B"],
  ["Which oxide is basic?", "CO₂", "SO₂", "K₂O", "NO", "C"],
  ["Which of the following is a neutral oxide?", "N₂O", "SO₂", "CaO", "Al₂O₃", "A"],
  ["Hydrides of nonmetals are usually:", "Ionic", "Covalent", "Metallic", "Amphoteric", "B"],
  ["Which of the following is an example of an acidic anhydride?", "Na₂O", "CaO", "SO₃", "Fe₂O₃", "C"],
  ["Which hydride is used as a reducing agent?", "CH₄", "NH₃", "NaH", "H₂O", "C"],

  // SET 14 — Properties of Elements and Their Compounds
  ["Alkali metals (Group IA) react vigorously with:", "Oxygen", "Water", "Nitrogen", "Noble gases", "B"],
  ["Which alkali metal is the most reactive?", "Lithium", "Sodium", "Potassium", "Cesium", "D"],
  ["Alkaline earth metals (Group IIA) have:", "One valence electron", "Two valence electrons", "Three valence electrons", "Four valence electrons", "B"],
  ["Which of the following is an alkaline earth metal?", "Na", "K", "Mg", "Li", "C"],
  ["Transition metals typically form:", "Only one oxidation state", "Multiple oxidation states", "No ions", "Only negative ions", "B"],
  ["Which element forms a green precipitate with NaOH?", "Fe²⁺", "Fe³⁺", "Cu²⁺", "Zn²⁺", "A"],
  ["Which ion forms a blue solution in water?", "Fe²⁺", "Fe³⁺", "Cu²⁺", "Zn²⁺", "C"],
  ["Zinc reacts with acids to produce:", "Oxygen", "Hydrogen gas", "Nitrogen gas", "Chlorine gas", "B"],
  ["Which metal is used for galvanization?", "Copper", "Zinc", "Iron", "Silver", "B"],
  ["Which metal is liquid at room temperature?", "Sodium", "Magnesium", "Mercury", "Zinc", "C"],
  ["Which of the following metals forms amphoteric hydroxides?", "Na", "Ca", "Al", "Fe", "C"],
  ["Copper(II) sulfate crystals are typically:", "White", "Blue", "Green", "Yellow", "B"],
  ["Iron rusting is an example of:", "Reduction", "Oxidation", "Neutralization", "Sublimation", "B"],
  ["Which metal reacts with cold water?", "Mg", "Ca", "Zn", "Cu", "B"],
  ["Which metal does NOT react with acids?", "Zn", "Fe", "Mg", "Cu", "D"],
  // SET 15 — Organic Chemistry Basics
  ["Organic compounds are primarily composed of:", "Carbon", "Nitrogen", "Sulfur", "Phosphorus", "A"],
  ["Hydrocarbons contain only:", "Carbon and oxygen", "Carbon and hydrogen", "Carbon and nitrogen", "Carbon and sulfur", "B"],
  ["Alkanes are hydrocarbons with:", "Single bonds only", "Double bonds only", "Triple bonds only", "Aromatic rings", "A"],
  ["Alkenes are hydrocarbons containing at least one:", "Single bond", "Double bond", "Triple bond", "Aromatic ring", "B"],
  ["Alkynes contain at least one:", "Single bond", "Double bond", "Triple bond", "Aromatic ring", "C"],
  ["The simplest alkane is:", "Ethane", "Methane", "Propane", "Butane", "B"],
  ["The functional group of alcohols is:", "–COOH", "–OH", "–NH₂", "–CHO", "B"],
  ["The functional group of carboxylic acids is:", "–OH", "–COOH", "–CHO", "–NH₂", "B"],
  ["The functional group of aldehydes is:", "–COOH", "–OH", "–CHO", "–COO–", "C"],
  ["The functional group of ketones is:", "–CO–", "–CHO", "–NH₂", "–OH", "A"],
  ["Aromatic compounds contain:", "Only single bonds", "Only double bonds", "A benzene ring", "No carbon atoms", "C"],
  ["Isomers are compounds that have:", "Different molecular formulas", "The same molecular formula but different structures", "The same structure", "Different types of atoms", "B"],
  ["Saturated hydrocarbons are those that contain:", "Double bonds", "Triple bonds", "Only single bonds", "Aromatic rings", "C"],
  ["Unsaturated hydrocarbons include:", "Alkanes", "Alkenes and alkynes", "Alcohols", "Ketones", "B"],
  ["The simplest aromatic hydrocarbon is:", "Methane", "Ethene", "Benzene", "Propane", "C"],

  // SET 16 — Organic Reactions
  ["Addition reactions are characteristic of:", "Alkanes", "Alkenes and alkynes", "Aromatic compounds", "Alcohols", "B"],
  ["Substitution reactions are typical of:", "Alkanes and aromatic compounds", "Alkenes only", "Alkynes only", "Carboxylic acids only", "A"],
  ["Combustion of hydrocarbons produces:", "CO₂ and H₂O", "CO and H₂", "H₂ and O₂", "CO₂ only", "A"],
  ["Hydrogenation of an alkene produces:", "An alkyne", "An alkane", "An alcohol", "A ketone", "B"],
  ["Halogenation of alkanes occurs via:", "Addition", "Substitution", "Elimination", "Oxidation", "B"],
  ["Hydration of an alkene produces:", "An alcohol", "An aldehyde", "A ketone", "An ether", "A"],
  ["Dehydration of alcohols typically forms:", "Alkanes", "Alkenes", "Alkynes", "Aromatic compounds", "B"],
  ["Oxidation of primary alcohols produces:", "Ketones", "Aldehydes", "Esters", "Alkanes", "B"],
  ["Oxidation of secondary alcohols produces:", "Aldehydes", "Ketones", "Carboxylic acids", "Alkenes", "B"],
  ["Oxidation of aldehydes produces:", "Ketones", "Carboxylic acids", "Alcohols", "Alkanes", "B"],
  ["Esterification is the reaction between:", "Alcohol + aldehyde", "Alcohol + carboxylic acid", "Alcohol + ketone", "Alcohol + alkene", "B"],
  ["Saponification is the hydrolysis of esters in the presence of:", "Acid", "Base", "Water only", "Alcohol", "B"],
  ["Cracking of hydrocarbons involves:", "Breaking large molecules into smaller ones", "Combining small molecules into larger ones", "Adding hydrogen", "Removing oxygen", "A"],
  ["Polymerization of alkenes is an example of:", "Addition reaction", "Substitution reaction", "Elimination reaction", "Oxidation reaction", "A"],
  ["Aromatic compounds typically undergo:", "Addition reactions", "Substitution reactions", "Combustion only", "Hydrogenation only", "B"],
  // SET 17 — Biomolecules
  ["Carbohydrates are composed of:", "C, H, O", "C, H, N", "C, N, O", "C, S, H", "A"],
  ["The simplest carbohydrates are called:", "Disaccharides", "Polysaccharides", "Monosaccharides", "Oligosaccharides", "C"],
  ["Glucose is an example of a:", "Disaccharide", "Monosaccharide", "Polysaccharide", "Lipid", "B"],
  ["Sucrose is composed of:", "Glucose + glucose", "Glucose + fructose", "Glucose + galactose", "Fructose + fructose", "B"],
  ["Starch is a:", "Monosaccharide", "Disaccharide", "Polysaccharide", "Lipid", "C"],
  ["Lipids are generally:", "Water‑soluble", "Insoluble in water", "Ionic compounds", "Polysaccharides", "B"],
  ["The building blocks of proteins are:", "Fatty acids", "Amino acids", "Monosaccharides", "Nucleotides", "B"],
  ["The bond between amino acids is called a:", "Glycosidic bond", "Peptide bond", "Ester bond", "Hydrogen bond", "B"],
  ["Enzymes are:", "Carbohydrates", "Lipids", "Proteins", "Nucleic acids", "C"],
  ["Enzymes act as:", "Catalysts", "Inhibitors", "Buffers", "Hormones only", "A"],
  ["The part of the enzyme where the substrate binds is the:", "Active site", "Binding pocket", "Reaction center", "Catalytic zone", "A"],
  ["Enzyme activity is affected by:", "Temperature", "pH", "Substrate concentration", "All of the above", "D"],
  ["DNA is composed of units called:", "Amino acids", "Nucleotides", "Fatty acids", "Monosaccharides", "B"],
  ["The sugar found in DNA is:", "Ribose", "Glucose", "Deoxyribose", "Fructose", "C"],
  ["The main function of lipids in the body is:", "Immediate energy", "Long‑term energy storage", "Catalysis", "Genetic information", "B"],

  // SET 18 — Nuclear Chemistry
  ["Radioactivity is the process by which unstable nuclei:", "Absorb energy", "Emit radiation", "Gain electrons", "Form ions", "B"],
  ["Alpha particles consist of:", "1 proton", "2 protons and 2 neutrons", "2 electrons", "1 neutron", "B"],
  ["Beta particles are:", "Helium nuclei", "Electrons", "Protons", "Neutrons", "B"],
  ["Gamma radiation is a form of:", "Particles", "Electromagnetic radiation", "Neutrons", "Protons", "B"],
  ["Which type of radiation has the highest penetrating power?", "Alpha", "Beta", "Gamma", "Neutron", "C"],
  ["Which type of radiation can be stopped by paper?", "Alpha", "Beta", "Gamma", "X‑rays", "A"],
  ["The half‑life of a radioactive isotope is the time required for:", "All atoms to decay", "Half of the atoms to decay", "One atom to decay", "The sample to double", "B"],
  ["A radioactive isotope with a short half‑life is:", "Very stable", "Highly unstable", "Non‑radioactive", "Chemically inert", "B"],
  ["Nuclear fission is the process of:", "Combining nuclei", "Splitting heavy nuclei", "Emitting electrons", "Absorbing neutrons without change", "B"],
  ["Nuclear fusion is the process of:", "Splitting nuclei", "Combining light nuclei", "Emitting alpha particles", "Producing beta particles", "B"],
  ["Which radiation carries a +2 charge?", "Alpha", "Beta", "Gamma", "Neutron", "A"],
  ["Which radiation carries a –1 charge?", "Alpha", "Beta", "Gamma", "Proton", "B"],
  ["The unit used to measure radioactivity is the:", "Joule", "Becquerel", "Pascal", "Watt", "B"],
  ["A radioactive decay series ends when:", "The nucleus becomes stable", "All particles are emitted", "The mass number becomes zero", "The atom becomes ionized", "A"],
  ["Carbon‑14 dating is used to determine the age of:", "Rocks", "Fossils and organic remains", "Metals", "Minerals", "B"],

  // SET 19 — Environmental Chemistry
  ["The main greenhouse gases include:", "N₂ and O₂", "CO₂ and CH₄", "He and Ne", "H₂ and Cl₂", "B"],
  ["Acid rain is primarily caused by:", "CO₂ and H₂O", "SO₂ and NOₓ", "O₃ and N₂", "CH₄ and CO", "B"],
  ["The pH of acid rain is typically:", "Above 7", "Exactly 7", "Below 5.6", "Above 10", "C"],
  ["Ozone (O₃) in the stratosphere protects us from:", "Infrared radiation", "Ultraviolet radiation", "Visible light", "Microwaves", "B"],
  ["Which gas is responsible for ozone layer depletion?", "CO₂", "CH₄", "CFCs", "N₂O", "C"],
  ["The greenhouse effect is caused by gases that:", "Reflect visible light", "Absorb infrared radiation", "Block ultraviolet light", "Produce ozone", "B"],
  ["Eutrophication of water bodies is caused by excess:", "Oxygen", "Nitrogen and phosphorus", "Carbon dioxide", "Chlorine", "B"],
  ["Which of the following is a primary air pollutant?", "Ozone", "Sulfur dioxide", "Nitric acid", "Peroxyacetyl nitrate", "B"],
  ["Biochemical Oxygen Demand (BOD) measures:", "Oxygen in the atmosphere", "Oxygen needed by microorganisms to decompose organic matter", "Oxygen produced by photosynthesis", "Oxygen in ozone", "B"],
  ["Hard water contains high concentrations of:", "Na⁺ and K⁺", "Ca²⁺ and Mg²⁺", "Fe³⁺ and Al³⁺", "H⁺ and OH⁻", "B"],
  ["Water softening can be achieved by:", "Adding more Ca²⁺", "Ion exchange", "Adding acid", "Boiling only", "B"],
  ["Which heavy metal is associated with Minamata disease?", "Lead", "Cadmium", "Mercury", "Arsenic", "C"],
  ["Photochemical smog is formed by the reaction of:", "CO₂ and water", "NOₓ and hydrocarbons in sunlight", "SO₂ and O₂", "CH₄ and Cl₂", "B"],
  ["The main component of natural gas is:", "Ethane", "Propane", "Methane", "Butane", "C"],
  ["Which process converts nitrogen gas into usable nitrogen compounds?", "Nitrification", "Nitrogen fixation", "Denitrification", "Ammonification", "B"],

  // SET 20 — Final Review (Mixed Chemistry)
  ["Which of the following has the highest ionization energy?", "Na", "Mg", "Al", "Ne", "D"],
  ["The bond angle in a tetrahedral molecule is approximately:", "90°", "109.5°", "120°", "180°", "B"],
  ["Which of the following is a Lewis acid?", "NH₃", "BF₃", "H₂O", "OH⁻", "B"],
  ["The molar mass of water (H₂O) is approximately:", "16 g/mol", "18 g/mol", "20 g/mol", "32 g/mol", "B"],
  ["Dalton's law of partial pressures states that:", "Total pressure equals the sum of partial pressures", "Pressure is inversely proportional to volume", "Pressure is proportional to temperature", "Gas molecules have no volume", "A"],
  ["Which of the following solutions has the lowest freezing point?", "0.1 M glucose", "0.1 M NaCl", "0.1 M CaCl₂", "0.1 M AlCl₃", "D"],
  ["The hybridization of carbon in methane (CH₄) is:", "sp", "sp²", "sp³", "sp³d", "C"],
  ["A reaction that absorbs heat from the surroundings is:", "Exothermic", "Endothermic", "Isothermal", "Adiabatic", "B"],
  ["The rate law of a reaction depends on:", "Products only", "Mechanism and experimental data", "Temperature only", "Pressure only", "B"],
  ["Which indicator is commonly used in acid–base titrations?", "Starch", "Phenolphthalein", "Methyl orange only in strong acid", "Litmus only", "B"],
  ["In a galvanic cell, electrons flow from:", "Cathode to anode", "Anode to cathode", "Salt bridge to anode", "Cathode to salt bridge", "B"],
  ["The IUPAC name of CH₃CH₂OH is:", "Methanol", "Ethanol", "Propanol", "Butanol", "B"],
  ["Which amino acid is the simplest?", "Alanine", "Glycine", "Valine", "Leucine", "B"],
  ["A peptide bond is formed by:", "Hydrolysis", "Condensation reaction", "Oxidation", "Reduction", "B"],
  ["The pH of a 0.01 M HCl solution is:", "1", "2", "3", "4", "B"],
];

// Insert all chemistry questions with shuffled answers
const insertChemistry = db.transaction(() => {
  shuffleAndInsert('chemistry', chemistryQuestions);
});
insertChemistry();

const biologyQuestions = [
  // CELL BIOLOGY — Questions 1–40
  ["Which structure is present in prokaryotic cells but absent in eukaryotic cells?", "Mitochondria", "Golgi apparatus", "Nucleoid region", "Endoplasmic reticulum", "C"],
  ["Which component of the cell membrane is primarily responsible for membrane fluidity?", "DNA", "Cellulose fibers", "Ribosomes", "Phospholipids", "D"],
  ["Which organelle is known as the 'powerhouse of the cell'?", "Ribosome", "Mitochondrion", "Golgi apparatus", "Lysosome", "B"],
  ["Which of the following is a characteristic of eukaryotic cells?", "Circular DNA", "Absence of nucleus", "70S ribosomes", "Presence of membrane-bound organelles", "D"],
  ["Which organelle is responsible for protein synthesis?", "Vacuole", "Ribosome", "Peroxisome", "Lysosome", "B"],
  ["During which phase of the cell cycle does DNA replication occur?", "S phase", "G1 phase", "M phase", "G2 phase", "A"],
  ["Which structure regulates movement of substances into and out of the nucleus?", "Centrioles", "Nuclear pores", "Chromatin", "Ribosomes", "B"],
  ["Which statement about viruses is correct?", "They are cellular organisms", "They contain both DNA and RNA at the same time", "They require a host cell to replicate", "They reproduce independently", "C"],
  ["Which organelle contains digestive enzymes for breaking down waste?", "Chloroplast", "Nucleolus", "Lysosome", "Smooth ER", "C"],
  ["Which structure is responsible for modifying and packaging proteins?", "Golgi apparatus", "Smooth ER", "Centrosome", "Rough ER", "A"],
  ["Which of the following distinguishes multicellular organisms from unicellular organisms?", "Only multicellular organisms have DNA", "Unicellular organisms cannot reproduce", "Unicellular organisms have more complex structures", "Multicellular organisms show cell specialization", "D"],
  ["Which bacterial structure enables movement?", "Flagellum", "Capsule", "Ribosome", "Pilus", "A"],
  ["Which organelle is the site of lipid synthesis?", "Golgi apparatus", "Smooth ER", "Mitochondrion", "Rough ER", "B"],
  ["What is the process of cytoplasmic division called?", "Meiosis", "Karyokinesis", "Replication", "Cytokinesis", "D"],
  ["Which bacterial component provides structural support and protection?", "Plasma membrane", "Nucleoid", "Capsule", "Cell wall", "D"],
  ["Which organelle is responsible for producing ATP in plant cells during photosynthesis?", "Mitochondrion", "Chloroplast", "Ribosome", "Golgi apparatus", "B"],
  ["What is the primary function of the rough endoplasmic reticulum?", "Lipid synthesis", "Detoxification", "Protein synthesis", "DNA replication", "C"],
  ["Which of the following best describes osmosis?", "Movement of solute from low to high concentration", "Movement of water from high to low concentration", "Movement of water across a membrane from low to high solute concentration", "Active transport of ions", "C"],
  ["Which structure anchors the cytoskeleton and organizes microtubules during cell division?", "Lysosome", "Centrosome", "Nucleolus", "Peroxisome", "B"],
  ["Which type of transport requires energy (ATP)?", "Diffusion", "Facilitated diffusion", "Osmosis", "Active transport", "D"],
  ["Which organelle contains its own DNA and ribosomes?", "Golgi apparatus", "Lysosome", "Mitochondrion", "Smooth ER", "C"],
  ["What is the main component of the cell wall in bacteria?", "Cellulose", "Peptidoglycan", "Chitin", "Lignin", "B"],
  ["Which phase of mitosis involves the chromosomes lining up at the cell's equator?", "Prophase", "Metaphase", "Anaphase", "Telophase", "B"],
  ["What is the function of the nucleolus?", "DNA replication", "Ribosome production", "Lipid synthesis", "Protein packaging", "B"],
  ["Which organelle is responsible for detoxifying harmful substances in liver cells?", "Rough ER", "Smooth ER", "Golgi apparatus", "Lysosome", "B"],
  ["What is the genetic material of most bacteria?", "Linear DNA", "Circular DNA", "RNA only", "DNA wrapped around histones", "B"],
  ["Which process results in two genetically identical daughter cells?", "Meiosis", "Binary fission", "Fertilization", "Crossing over", "B"],
  ["Which organelle is responsible for maintaining turgor pressure in plant cells?", "Chloroplast", "Central vacuole", "Mitochondrion", "Ribosome", "B"],
  ["What is the main role of ribosomal RNA (rRNA)?", "Carries genetic code", "Catalyzes peptide bond formation", "Transports amino acids", "Regulates gene expression", "B"],
  ["Which structure forms the boundary between the cell and its environment?", "Cytoplasm", "Cell membrane", "Nucleus", "Golgi apparatus", "B"],
  ["Which molecule passes most easily through the cell membrane?", "Glucose", "Sodium ions", "Oxygen", "Proteins", "C"],
  ["What is the main function of peroxisomes?", "Protein synthesis", "Detoxification of hydrogen peroxide", "ATP production", "Lipid transport", "B"],
  ["Which cytoskeletal element is responsible for muscle contraction?", "Microtubules", "Intermediate filaments", "Actin filaments", "Centrioles", "C"],
  ["Which organelle is responsible for sorting and directing vesicles to their destinations?", "Ribosome", "Golgi apparatus", "Lysosome", "Nucleus", "B"],
  ["What is the function of the cell membrane's cholesterol molecules?", "Increase membrane permeability", "Stabilize membrane fluidity", "Transport ions", "Produce ATP", "B"],
  ["Which process moves large particles into the cell via vesicles?", "Exocytosis", "Endocytosis", "Osmosis", "Diffusion", "B"],
  ["Which structure is responsible for forming spindle fibers during mitosis?", "Nucleolus", "Centrosome", "Lysosome", "Golgi apparatus", "B"],
  ["What is the primary function of the cytoplasm?", "Store genetic material", "Provide a medium for chemical reactions", "Produce proteins", "Package cellular products", "B"],
  ["Which organelle is abundant in cells that secrete large amounts of proteins?", "Smooth ER", "Rough ER", "Lysosome", "Chloroplast", "B"],
  ["Which type of RNA carries amino acids to the ribosome during translation?", "mRNA", "rRNA", "tRNA", "snRNA", "C"],

  // DEVELOPMENTAL BIOLOGY — Questions 1–35
  ["What is the process of forming gametes called?", "Fertilization", "Gametogenesis", "Cleavage", "Gastrulation", "B"],
  ["Which process produces sperm cells in males?", "Oogenesis", "Mitosis", "Spermatogenesis", "Fertilization", "C"],
  ["Where does oogenesis occur in humans?", "Testes", "Ovaries", "Uterus", "Fallopian tubes", "B"],
  ["What is the fusion of sperm and egg called?", "Cleavage", "Fertilization", "Implantation", "Induction", "B"],
  ["What is the first stage after fertilization?", "Gastrulation", "Organogenesis", "Cleavage", "Neurulation", "C"],
  ["What is the purpose of cleavage divisions?", "Increase embryo size", "Form a multicellular embryo", "Produce gametes", "Form organs", "B"],
  ["Gastrulation results in the formation of:", "Gametes", "Three germ layers", "Placenta", "Notochord", "B"],
  ["Which germ layer gives rise to the nervous system?", "Endoderm", "Mesoderm", "Ectoderm", "Hypoderm", "C"],
  ["The notochord is derived from which germ layer?", "Ectoderm", "Mesoderm", "Endoderm", "None of the above", "B"],
  ["Organogenesis begins with the formation of which structure?", "Blastula", "Neural tube", "Morula", "Zygote", "B"],
  ["What is embryonic induction?", "Formation of gametes", "One group of cells influencing the development of another", "Cell death", "DNA replication", "B"],
  ["What is the function of the placenta?", "Produce gametes", "Exchange nutrients and gases between mother and embryo", "Form the neural tube", "Produce hormones for puberty", "B"],
  ["Which type of placenta is characteristic of humans?", "Diffuse", "Cotyledonary", "Discoidal", "Zonary", "C"],
  ["What is cell differentiation?", "Cells dividing rapidly", "Cells becoming specialized in structure and function", "Cells dying", "Cells fusing together", "B"],
  ["Fate mapping is used to determine:", "The number of chromosomes", "The future developmental path of embryonic cells", "The sex of the embryo", "The rate of cell division", "B"],
  ["What is the term for the ability of an embryonic cell to develop into many different cell types?", "Differentiation", "Potency", "Induction", "Cleavage", "B"],
  ["Totipotent cells can develop into:", "Only body tissues", "Only extraembryonic tissues", "Both body and extraembryonic tissues", "Only nervous tissue", "C"],
  ["Which structure forms first during neurulation?", "Neural tube", "Notochord", "Somites", "Blastocoel", "B"],
  ["The neural tube eventually develops into the:", "Digestive tract", "Circulatory system", "Brain and spinal cord", "Muscular system", "C"],
  ["Which germ layer gives rise to the lining of the digestive tract?", "Ectoderm", "Mesoderm", "Endoderm", "Hypoderm", "C"],
  ["What is the morula?", "A hollow ball of cells", "A solid ball of cells", "A fertilized egg", "A three-layered embryo", "B"],
  ["The blastocyst implants into the uterus during which stage?", "Cleavage", "Gastrulation", "Organogenesis", "Early embryogenesis", "D"],
  ["Which structure becomes the embryo's digestive tube?", "Neural crest", "Archenteron", "Blastocoel", "Chorion", "B"],
  ["What is the function of the amnion?", "Gas exchange", "Nutrient transport", "Protection of the embryo in fluid", "Waste storage", "C"],
  ["Which extraembryonic membrane forms the umbilical cord blood vessels?", "Amnion", "Chorion", "Allantois", "Yolk sac", "C"],
  ["Which process describes cells moving to new positions during gastrulation?", "Involution", "Apoptosis", "Cleavage", "Induction", "A"],
  ["What is the primary role of the chorion in mammals?", "Forming the placenta", "Producing amniotic fluid", "Digesting yolk", "Forming the neural tube", "A"],
  ["Which hormone maintains pregnancy in early stages?", "LH", "FSH", "hCG", "Oxytocin", "C"],
  ["What is senescence?", "Rapid cell division", "Programmed cell death", "The process of aging", "Formation of gametes", "C"],
  ["Human development from birth to adulthood is called:", "Embryogenesis", "Organogenesis", "Individual development", "Morphogenesis", "C"],
  ["What is the primary function of the yolk sac in early human development?", "Gas exchange", "Early blood cell formation", "Waste storage", "Hormone production", "B"],
  ["Which process describes programmed cell death during development?", "Cleavage", "Apoptosis", "Induction", "Differentiation", "B"],
  ["Which structure forms the basis of the vertebral column?", "Neural crest", "Notochord", "Somites", "Endoderm", "B"],
  ["What is the main purpose of organogenesis?", "Formation of gametes", "Formation of organs and organ systems", "Formation of the placenta", "Formation of the blastula", "B"],
  ["Which factor most strongly influences the determination of cell fate during early development?", "Temperature", "Cytoplasmic determinants", "Blood supply", "Amniotic fluid", "B"],

  // ANIMAL MORPHOLOGY — Questions 1–30
  ["Which system is responsible for transporting nutrients and oxygen throughout the body?", "Nervous system", "Circulatory system", "Digestive system", "Excretory system", "B"],
  ["Which organ is the primary site of gas exchange in mammals?", "Trachea", "Bronchi", "Alveoli", "Larynx", "C"],
  ["Which part of the nervous system controls voluntary movements?", "Autonomic nervous system", "Sympathetic nervous system", "Parasympathetic nervous system", "Somatic nervous system", "D"],
  ["Which structure filters blood and produces urine?", "Liver", "Kidney", "Pancreas", "Spleen", "B"],
  ["Which type of muscle is found in the walls of internal organs?", "Skeletal muscle", "Cardiac muscle", "Smooth muscle", "Voluntary muscle", "C"],
  ["Which organ secretes digestive enzymes and hormones such as insulin?", "Liver", "Pancreas", "Gallbladder", "Stomach", "B"],
  ["What is the main function of the endocrine system?", "Transport oxygen", "Produce movement", "Regulate body functions through hormones", "Remove waste", "C"],
  ["Which structure connects muscles to bones?", "Ligaments", "Tendons", "Cartilage", "Fascia", "B"],
  ["Which organ is responsible for mechanical digestion through churning?", "Small intestine", "Stomach", "Liver", "Esophagus", "B"],
  ["Which part of the brain controls balance and coordination?", "Cerebrum", "Cerebellum", "Medulla oblongata", "Hypothalamus", "B"],
  ["Which blood vessels carry blood away from the heart?", "Veins", "Arteries", "Capillaries", "Venules", "B"],
  ["Which sense organ contains photoreceptor cells?", "Ear", "Nose", "Eye", "Skin", "C"],
  ["Which structure prevents food from entering the trachea during swallowing?", "Epiglottis", "Larynx", "Pharynx", "Uvula", "A"],
  ["Which system is responsible for maintaining body temperature?", "Digestive system", "Respiratory system", "Nervous and endocrine systems", "Excretory system", "C"],
  ["Which organ stores bile produced by the liver?", "Pancreas", "Gallbladder", "Stomach", "Large intestine", "B"],
  ["Which structure is responsible for filtering lymph and housing immune cells?", "Liver", "Spleen", "Lymph nodes", "Pancreas", "C"],
  ["Which type of blood cell is primarily responsible for oxygen transport?", "White blood cells", "Platelets", "Red blood cells", "Plasma cells", "C"],
  ["Which organ is the main site of nutrient absorption?", "Stomach", "Small intestine", "Large intestine", "Esophagus", "B"],
  ["Which part of the ear is responsible for detecting sound vibrations?", "Cochlea", "Semicircular canals", "Eardrum", "Auditory nerve", "A"],
  ["Which hormone is produced by the thyroid gland?", "Insulin", "Thyroxine", "Cortisol", "Glucagon", "B"],
  ["Which structure connects bones to other bones?", "Tendons", "Ligaments", "Cartilage", "Fascia", "B"],
  ["Which organ removes old or damaged red blood cells from circulation?", "Kidney", "Liver", "Spleen", "Pancreas", "C"],
  ["Which part of the respiratory system warms, moistens, and filters incoming air?", "Bronchi", "Nasal cavity", "Alveoli", "Trachea", "B"],
  ["Which structure in the eye regulates the amount of light entering the pupil?", "Retina", "Lens", "Iris", "Cornea", "C"],
  ["Which organ produces bile?", "Pancreas", "Liver", "Gallbladder", "Stomach", "B"],
  ["Which part of the brain controls involuntary functions such as breathing and heart rate?", "Cerebrum", "Cerebellum", "Medulla oblongata", "Hypothalamus", "C"],
  ["Which system is responsible for removing metabolic waste from the body?", "Digestive system", "Excretory system", "Endocrine system", "Nervous system", "B"],
  ["Which structure increases the surface area of the small intestine for absorption?", "Villi", "Alveoli", "Nephrons", "Cilia", "A"],
  ["Which organ is responsible for producing sound in humans?", "Pharynx", "Larynx", "Trachea", "Bronchi", "B"],
  ["Which gland is known as the 'master gland' of the endocrine system?", "Thyroid gland", "Adrenal gland", "Pituitary gland", "Pineal gland", "C"],

  // MOLECULAR BIOLOGY — Questions 1–45
  ["Which molecule stores genetic information in most organisms?", "RNA", "DNA", "Protein", "Lipid", "B"],
  ["What is the basic unit of a nucleic acid?", "Amino acid", "Fatty acid", "Nucleotide", "Monosaccharide", "C"],
  ["Which nitrogenous bases are found in DNA?", "A, U, G, C", "A, T, G, C", "A, U, G, T", "A, C, U, T", "B"],
  ["Which enzyme unwinds the DNA double helix during replication?", "DNA polymerase", "Helicase", "Ligase", "Primase", "B"],
  ["Which process converts DNA into mRNA?", "Translation", "Replication", "Transcription", "Mutation", "C"],
  ["Which organelle is the site of protein synthesis?", "Golgi apparatus", "Ribosome", "Lysosome", "Mitochondrion", "B"],
  ["What is the function of tRNA?", "Carry amino acids to the ribosome", "Carry genetic code to the nucleus", "Form ribosomes", "Replicate DNA", "A"],
  ["The genetic code is described as:", "Overlapping", "Ambiguous", "Universal", "Species-specific", "C"],
  ["Which enzyme adds nucleotides during DNA replication?", "DNA polymerase", "RNA polymerase", "Ligase", "Helicase", "A"],
  ["Which type of RNA forms the core of the ribosome?", "mRNA", "tRNA", "rRNA", "snRNA", "C"],
  ["What is a codon?", "A protein-binding site", "A three-base sequence on mRNA", "A DNA repair enzyme", "A type of mutation", "B"],
  ["Which process occurs in the cytoplasm of eukaryotic cells?", "DNA replication", "Transcription", "Translation", "RNA processing", "C"],
  ["Which bond holds the two DNA strands together?", "Ionic bonds", "Hydrogen bonds", "Peptide bonds", "Covalent bonds", "B"],
  ["What is the role of DNA ligase?", "Unwind DNA", "Join Okazaki fragments", "Add RNA primers", "Remove introns", "B"],
  ["Which molecule carries the genetic code from the nucleus to the ribosome?", "tRNA", "rRNA", "mRNA", "snRNA", "C"],
  ["What is the central dogma of molecular biology?", "DNA → RNA → Protein", "Protein → RNA → DNA", "RNA → DNA → Protein", "DNA → Protein → RNA", "A"],
  ["Which enzyme synthesizes RNA from a DNA template?", "DNA polymerase", "RNA polymerase", "Ligase", "Helicase", "B"],
  ["What is an intron?", "A coding region of a gene", "A non-coding region removed from pre-mRNA", "A type of tRNA", "A DNA repair enzyme", "B"],
  ["Which process removes introns from pre-mRNA?", "Translation", "Splicing", "Replication", "Transcription", "B"],
  ["Which molecule carries amino acids to the ribosome?", "mRNA", "rRNA", "tRNA", "snRNA", "C"],
  ["What is a mutation?", "A change in DNA sequence", "A type of RNA", "A protein modification", "A DNA repair mechanism", "A"],
  ["Which type of mutation does NOT change the amino acid sequence?", "Missense mutation", "Nonsense mutation", "Silent mutation", "Frameshift mutation", "C"],
  ["What is a promoter?", "A protein that binds DNA", "A region of DNA where transcription begins", "A type of RNA polymerase", "A DNA repair enzyme", "B"],
  ["Which enzyme seals breaks in the sugar-phosphate backbone of DNA?", "Helicase", "Ligase", "Primase", "Polymerase", "B"],
  ["What is the function of the anticodon on tRNA?", "Bind amino acids", "Bind mRNA codons", "Form ribosomes", "Replicate DNA", "B"],
  ["Which structure of a protein refers to its amino acid sequence?", "Primary structure", "Secondary structure", "Tertiary structure", "Quaternary structure", "A"],
  ["Alpha helices and beta sheets are examples of:", "Primary structure", "Secondary structure", "Tertiary structure", "Quaternary structure", "B"],
  ["Which molecule is responsible for forming peptide bonds during translation?", "DNA polymerase", "Peptidyl transferase (part of rRNA)", "RNA polymerase", "Helicase", "B"],
  ["What is a genome?", "All proteins in a cell", "All RNA molecules in a cell", "All genetic material of an organism", "All lipids in a cell", "C"],
  ["Which technique is used to amplify DNA fragments?", "Gel electrophoresis", "PCR", "Western blot", "Chromatography", "B"],
  ["Which technique separates DNA fragments based on size?", "PCR", "Gel electrophoresis", "Western blot", "Chromatography", "B"],
  ["Which enzyme synthesizes short RNA primers during DNA replication?", "Ligase", "Primase", "Helicase", "Polymerase", "B"],
  ["What is a plasmid?", "A viral protein", "A small circular DNA molecule in bacteria", "A type of RNA", "A protein-coding region", "B"],
  ["Which molecule is responsible for regulating gene expression by binding to DNA?", "Ribosome", "Transcription factor", "tRNA", "Helicase", "B"],
  ["What is a restriction enzyme?", "An enzyme that synthesizes RNA", "An enzyme that cuts DNA at specific sequences", "An enzyme that repairs DNA", "An enzyme that unwinds DNA", "B"],
  ["Which process converts mRNA into a protein?", "Replication", "Transcription", "Translation", "Splicing", "C"],
  ["What is a point mutation?", "A deletion of many bases", "A duplication of a chromosome", "A change in a single nucleotide", "A rearrangement of genes", "C"],
  ["Which structure of a protein is determined by interactions between R-groups?", "Primary", "Secondary", "Tertiary", "Quaternary", "C"],
  ["Which molecule acts as the template during transcription?", "mRNA", "tRNA", "DNA", "Protein", "C"],
  ["What is the function of RNA polymerase?", "Add DNA nucleotides", "Add RNA nucleotides", "Form peptide bonds", "Cut DNA", "B"],
  ["Which type of RNA carries the genetic code for protein synthesis?", "rRNA", "tRNA", "mRNA", "snRNA", "C"],
  ["What is a gene?", "A lipid molecule", "A segment of DNA that codes for a protein", "A type of RNA", "A protein-binding enzyme", "B"],
  ["Which molecule forms the phospholipid bilayer of cell membranes?", "Proteins", "Lipids", "Carbohydrates", "Nucleic acids", "B"],
  ["What is recombinant DNA?", "DNA from viruses", "DNA formed by combining genetic material from different sources", "DNA that cannot replicate", "DNA without introns", "B"],
  ["Which technique is used to determine the sequence of nucleotides in DNA?", "PCR", "DNA sequencing", "Gel electrophoresis", "Western blot", "B"],

  // INHERITANCE MECHANISMS (GENETICS) — Questions 1–55
  ["What is genetics?", "Study of cells", "Study of heredity and variation", "Study of evolution", "Study of ecosystems", "B"],
  ["What is a gene?", "A protein molecule", "A segment of DNA that codes for a trait", "A type of RNA", "A chromosome", "B"],
  ["What is a phenotype?", "Genetic makeup of an organism", "Physical expression of a trait", "Number of chromosomes", "DNA sequence", "B"],
  ["What is a genotype?", "Observable characteristics", "Environmental influence", "Genetic composition of an organism", "Protein structure", "C"],
  ["Which term describes different forms of the same gene?", "Chromatids", "Alleles", "Loci", "Gametes", "B"],
  ["What is Mendel's Law of Segregation?", "Alleles separate during gamete formation", "Alleles are inherited together", "Genes blend during inheritance", "Dominant traits skip generations", "A"],
  ["What is Mendel's Law of Independent Assortment?", "Genes on the same chromosome are inherited together", "Alleles separate randomly into gametes", "Genes for different traits assort independently", "Dominant alleles mask recessive ones", "C"],
  ["Which type of inheritance shows both alleles expressed equally (e.g., AB blood type)?", "Incomplete dominance", "Codominance", "Polygenic inheritance", "Sex-linked inheritance", "B"],
  ["Which inheritance pattern results in a blended phenotype (e.g., pink flowers)?", "Codominance", "Incomplete dominance", "Dominant-recessive", "Polygenic", "B"],
  ["What is a karyotype?", "A DNA sequence", "A picture of chromosomes", "A type of mutation", "A gene map", "B"],
  ["What is recombination?", "DNA replication", "Exchange of genetic material between homologous chromosomes", "Mutation of genes", "Formation of gametes", "B"],
  ["What is a mutation?", "A change in DNA sequence", "A type of protein", "A chromosome map", "A dominant allele", "A"],
  ["Which chromosome pair determines biological sex in humans?", "Pair 1", "Pair 13", "Pair 21", "Pair 23", "D"],
  ["What is a sex-linked trait?", "Trait found only in males", "Trait found only in females", "Trait controlled by genes on sex chromosomes", "Trait controlled by autosomes", "C"],
  ["What is polygenic inheritance?", "One gene controlling many traits", "Many genes controlling one trait", "One gene controlling one trait", "Traits inherited only from the mother", "B"],
  ["What is a homozygous genotype?", "Two different alleles", "Two identical alleles", "One dominant and one recessive allele", "A mutation in a gene", "B"],
  ["What is a heterozygous genotype?", "Two identical alleles", "Two different alleles", "Only recessive alleles", "Only dominant alleles", "B"],
  ["Which allele is expressed in a heterozygous individual?", "Recessive allele", "Dominant allele", "Both alleles", "Neither allele", "B"],
  ["What is a Punnett square used for?", "Measuring DNA length", "Predicting genetic crosses", "Identifying mutations", "Counting chromosomes", "B"],
  ["What is a test cross used to determine?", "Phenotype", "Sex of an organism", "Unknown genotype", "Chromosome number", "C"],
  ["What is linkage?", "Genes located on different chromosomes", "Genes located close together on the same chromosome", "Genes that mutate together", "Genes that assort independently", "B"],
  ["What increases genetic variation during meiosis?", "DNA replication", "Crossing over", "Mitosis", "Cytokinesis", "B"],
  ["What is nondisjunction?", "Failure of chromosomes to separate properly", "Exchange of genetic material", "Mutation of DNA", "Formation of gametes", "A"],
  ["Down syndrome is caused by:", "Trisomy 13", "Trisomy 18", "Trisomy 21", "Monosomy X", "C"],
  ["What is a pedigree used for?", "Measuring DNA", "Tracing inheritance of traits in families", "Identifying proteins", "Counting alleles", "B"],
  ["Which type of inheritance shows traits more often in males?", "Autosomal dominant", "Autosomal recessive", "X-linked recessive", "Y-linked dominant", "C"],
  ["What is an autosome?", "A sex chromosome", "A chromosome not involved in sex determination", "A mutated chromosome", "A duplicated chromosome", "B"],
  ["What is a carrier?", "An individual with two dominant alleles", "An individual with two recessive alleles", "A heterozygous individual who carries a recessive allele", "An individual with a mutation", "C"],
  ["Which type of inheritance involves multiple genes affecting one trait?", "Codominance", "Polygenic inheritance", "Sex-linked inheritance", "Dominant-recessive", "B"],
  ["Skin color in humans is an example of:", "Codominance", "Polygenic inheritance", "Sex-linked inheritance", "Monogenic inheritance", "B"],
  ["What is epistasis?", "One gene masking the expression of another gene", "Two genes blending together", "A mutation in a dominant allele", "A trait inherited only from the father", "A"],
  ["What is a dihybrid cross?", "A cross involving one trait", "A cross involving two traits", "A cross involving sex-linked traits", "A cross involving mutations", "B"],
  ["What is the expected phenotypic ratio of a dihybrid cross (AaBb x AaBb)?", "1:1", "3:1", "9:3:3:1", "1:2:1", "C"],
  ["What is a chromosome?", "A protein molecule", "A long DNA molecule with associated proteins", "A type of RNA", "A lipid structure", "B"],
  ["What is crossing over?", "Exchange of DNA between sister chromatids", "Exchange of DNA between homologous chromosomes", "Mutation of DNA", "Formation of gametes", "B"],
  ["What is a locus?", "A type of mutation", "The location of a gene on a chromosome", "A dominant allele", "A recessive allele", "B"],
  ["What is a monohybrid cross?", "A cross involving two traits", "A cross involving one trait", "A cross involving sex chromosomes", "A cross involving mutations", "B"],
  ["What is incomplete dominance?", "Both alleles fully expressed", "One allele completely masks the other", "Heterozygote shows an intermediate phenotype", "Only recessive alleles are expressed", "C"],
  ["What is a dominant allele?", "An allele expressed only when homozygous", "An allele expressed in both homozygous and heterozygous states", "An allele that mutates frequently", "An allele found only on sex chromosomes", "B"],
  ["What is a recessive allele?", "Expressed only in heterozygotes", "Expressed only when two copies are present", "Always masked by dominant alleles", "Found only in males", "B"],
  ["What is a genetic disorder?", "A disease caused by environmental factors", "A disease caused by abnormalities in genes or chromosomes", "A temporary illness", "A viral infection", "B"],
  ["Hemophilia is an example of:", "Autosomal dominant inheritance", "Autosomal recessive inheritance", "X-linked recessive inheritance", "Y-linked inheritance", "C"],
  ["What is gene mapping?", "Identifying proteins", "Determining the location of genes on chromosomes", "Counting chromosomes", "Sequencing RNA", "B"],
  ["What is a frameshift mutation?", "A mutation that changes one base", "A mutation that adds or deletes bases, shifting the reading frame", "A mutation that stops translation", "A mutation that changes amino acid sequence without effect", "B"],
  ["What is genetic drift?", "Change in allele frequencies due to random events", "Change in allele frequencies due to natural selection", "Mutation of DNA", "Migration of individuals", "A"],
  ["What is gene flow?", "Random change in allele frequencies", "Movement of alleles between populations", "Mutation of DNA", "Natural selection", "B"],
  ["What is natural selection?", "Random mating", "Differential survival and reproduction of individuals", "Random changes in allele frequencies", "Movement of genes between populations", "B"],
  ["What is a genetic bottleneck?", "Increase in population size", "Sudden reduction in population size leading to loss of genetic variation", "Increase in mutation rate", "Formation of new species", "B"],
  ["What is a founder effect?", "Mutation in a large population", "Genetic variation increasing due to migration", "Small group starting a new population with limited genetic diversity", "Random mating", "C"],
  ["What is a quantitative trait?", "Trait controlled by one gene", "Trait controlled by multiple genes and influenced by environment", "Trait found only in males", "Trait that cannot be measured", "B"],
  ["What is heritability?", "The proportion of variation due to environmental factors", "The proportion of variation due to genetic factors", "The number of alleles in a population", "The mutation rate of a gene", "B"],
  ["What is a chromosomal inversion?", "A piece of chromosome breaks off", "A piece of chromosome flips and reinserts", "A chromosome is duplicated", "A chromosome is lost", "B"],
  ["What is a translocation?", "Exchange of segments between non-homologous chromosomes", "Exchange between sister chromatids", "Loss of a chromosome", "Duplication of a gene", "A"],
  ["What is genomic imprinting?", "Genes expressed only in males", "Genes expressed only in females", "Expression of a gene depending on whether it is inherited from the mother or father", "Genes that mutate frequently", "C"],
  ["What is pleiotropy?", "One gene affecting multiple traits", "Multiple genes affecting one trait", "Genes located on sex chromosomes", "Genes that assort independently", "A"],

  // EVOLUTIONARY MECHANISMS — Questions 1–40
  ["What is evolution?", "Change in individuals over their lifetime", "Change in allele frequencies in a population over time", "Sudden appearance of new species", "Random mutation only", "B"],
  ["Who proposed the theory of natural selection?", "Mendel", "Darwin", "Watson", "Lamarck", "B"],
  ["What is natural selection based on?", "Random mating", "Differential survival and reproduction", "Equal reproductive success", "Identical genetic makeup", "B"],
  ["Which of the following increases genetic variation?", "Natural selection", "Genetic drift", "Mutation", "Inbreeding", "C"],
  ["What is adaptation?", "A random mutation", "A trait that increases fitness in a specific environment", "A harmful trait", "A temporary physiological change", "B"],
  ["What is fitness in evolutionary terms?", "Physical strength", "Ability to survive and reproduce", "Ability to avoid predators", "Ability to migrate", "B"],
  ["What is gene flow?", "Random changes in allele frequencies", "Movement of alleles between populations", "Mutation of DNA", "Non-random mating", "B"],
  ["What is genetic drift?", "Change in allele frequencies due to random events", "Change due to natural selection", "Movement of individuals", "Mutation", "A"],
  ["The founder effect is a type of:", "Mutation", "Natural selection", "Genetic drift", "Gene flow", "C"],
  ["What is speciation?", "Formation of new genes", "Formation of new species", "Mutation of DNA", "Extinction of species", "B"],
  ["What is allopatric speciation?", "Speciation without geographic isolation", "Speciation due to hybridization", "Speciation due to geographic separation", "Speciation caused by mutation only", "C"],
  ["What is sympatric speciation?", "Speciation due to geographic barriers", "Speciation within the same geographic area", "Speciation caused by migration", "Speciation caused by extinction", "B"],
  ["What is a fossil?", "Living organism", "Preserved remains or traces of ancient life", "A mutation", "A type of mineral", "B"],
  ["What does the Hardy-Weinberg equilibrium describe?", "Evolution occurring rapidly", "Conditions under which allele frequencies remain constant", "Mutation rates", "Natural selection", "B"],
  ["Which of the following is NOT a condition of Hardy-Weinberg equilibrium?", "Large population", "No mutation", "Random mating", "Natural selection", "D"],
  ["What is adaptive radiation?", "Evolution of similar traits in unrelated species", "Rapid diversification of species from a common ancestor", "Slow evolutionary change", "Loss of genetic variation", "B"],
  ["What is convergent evolution?", "Species diverging from a common ancestor", "Unrelated species evolving similar traits", "Species becoming genetically identical", "Evolution occurring only through mutation", "B"],
  ["What is divergent evolution?", "Unrelated species becoming similar", "Related species becoming more different over time", "Species merging into one", "Evolution without natural selection", "B"],
  ["What is coevolution?", "Evolution of one species affecting another", "Evolution occurring randomly", "Evolution without mutation", "Evolution only in plants", "A"],
  ["What is sexual selection?", "Selection based on survival only", "Selection based on mating success", "Random mating", "Mutation-driven evolution", "B"],
  ["Which of the following is an example of sexual selection?", "Camouflage in insects", "Bright plumage in male birds", "Antibiotic resistance", "Genetic drift", "B"],
  ["What is artificial selection?", "Natural selection in the wild", "Human-directed breeding of organisms", "Random mating", "Mutation-driven evolution", "B"],
  ["What is a selective pressure?", "A random event", "A factor that influences survival or reproduction", "A mutation", "A type of gene flow", "B"],
  ["What is stabilizing selection?", "Favors extreme phenotypes", "Favors intermediate phenotypes", "Favors rare phenotypes", "Eliminates all variation", "B"],
  ["What is directional selection?", "Favors one extreme phenotype", "Favors both extremes", "Favors intermediate phenotypes", "Favors only recessive traits", "A"],
  ["What is disruptive selection?", "Favors intermediate phenotypes", "Favors both extreme phenotypes", "Eliminates extreme phenotypes", "Favors only recessive traits", "B"],
  ["What is a phylogenetic tree?", "A map of ecosystems", "A diagram showing evolutionary relationships", "A DNA sequence", "A fossil record", "B"],
  ["What is homologous structure?", "Similar function, different origin", "Similar origin, different function", "Identical in all species", "Found only in plants", "B"],
  ["What is analogous structure?", "Same origin, different function", "Different origin, similar function", "Identical in all species", "Found only in mammals", "B"],
  ["What is a molecular clock used for?", "Measuring mutation rates to estimate evolutionary time", "Measuring lifespan", "Counting chromosomes", "Determining phenotype", "A"],
  ["What is punctuated equilibrium?", "Evolution occurs slowly and steadily", "Evolution occurs in rapid bursts followed by long periods of stability", "Evolution stops completely", "Evolution occurs only through mutation", "B"],
  ["What is gradualism?", "Evolution occurs in sudden bursts", "Evolution occurs slowly and continuously over long periods", "Evolution occurs only in small populations", "Evolution occurs only through natural selection", "B"],
  ["What is extinction?", "Formation of new species", "Disappearance of a species", "Mutation of DNA", "Migration of individuals", "B"],
  ["What is a transitional fossil?", "A fossil that shows no evolutionary change", "A fossil showing traits of both ancestral and derived species", "A fossil found only in deep oceans", "A fossil that cannot be dated", "B"],
  ["What is microevolution?", "Evolution above the species level", "Evolution within populations over short timescales", "Evolution that creates new kingdoms", "Evolution caused only by mutation", "B"],
  ["What is macroevolution?", "Small genetic changes within a population", "Large-scale evolutionary changes leading to new species or groups", "Evolution caused only by natural selection", "Evolution that occurs only in plants", "B"],
  ["What is a gene pool?", "All genes in an individual", "All genes in a population", "All genes in an ecosystem", "All genes in a species", "B"],
  ["What is hybridization?", "Formation of identical species", "Crossing individuals from different species or populations", "Mutation of DNA", "Extinction of species", "B"],
  ["What is adaptive advantage?", "A trait that reduces survival", "A trait that increases survival or reproduction", "A trait that has no effect", "A harmful mutation", "B"],
  ["What is the main source of new genetic variation?", "Natural selection", "Mutation", "Migration", "Genetic drift", "B"],

  // ECOLOGY — Questions 1–40
  ["What is ecology?", "Study of cells", "Study of interactions between organisms and their environment", "Study of fossils", "Study of evolution", "B"],
  ["What is a population?", "All species in an area", "All individuals of one species in an area", "All ecosystems on Earth", "A group of ecosystems", "B"],
  ["What is a community?", "All abiotic factors in an area", "All populations of different species in an area", "A single species", "A biome", "B"],
  ["What is an ecosystem?", "Only living organisms", "Only non-living factors", "Living organisms plus their physical environment", "A single population", "C"],
  ["What is a biome?", "A small habitat", "A large region with similar climate and communities", "A single species", "A food chain", "B"],
  ["What is the biosphere?", "All ecosystems on Earth", "A single ecosystem", "A single community", "A single population", "A"],
  ["What is a habitat?", "The role of an organism", "The place where an organism lives", "A food chain", "A biome", "B"],
  ["What is a niche?", "The physical location of an organism", "The role and position of an organism in its environment", "A type of ecosystem", "A predator-prey relationship", "B"],
  ["What is a producer?", "An organism that eats others", "An organism that decomposes matter", "An organism that makes its own food", "An organism that migrates", "C"],
  ["What is a consumer?", "An organism that produces energy", "An organism that eats other organisms", "An organism that decomposes dead matter", "An organism that photosynthesizes", "B"],
  ["What is a decomposer?", "Organism that produces food", "Organism that eats plants", "Organism that breaks down dead matter", "Organism that migrates", "C"],
  ["What is a food chain?", "A network of all feeding relationships", "A linear sequence of who eats whom", "A group of producers", "A group of decomposers", "B"],
  ["What is a food web?", "A single feeding pathway", "A complex network of interconnected food chains", "A group of predators", "A group of herbivores", "B"],
  ["What is trophic level?", "A type of habitat", "A level in a food chain or web", "A type of biome", "A nutrient cycle", "B"],
  ["Which organisms occupy the first trophic level?", "Herbivores", "Carnivores", "Producers", "Decomposers", "C"],
  ["What is an energy pyramid?", "Diagram showing population sizes", "Diagram showing energy flow between trophic levels", "Diagram showing nutrient cycles", "Diagram showing climate zones", "B"],
  ["Which trophic level contains the most energy?", "Producers", "Primary consumers", "Secondary consumers", "Tertiary consumers", "A"],
  ["What happens to energy as it moves up trophic levels?", "It increases", "It stays the same", "It decreases", "It disappears completely", "C"],
  ["What is biomass?", "Total number of organisms", "Total mass of living organisms in an area", "Total amount of water in an ecosystem", "Total number of predators", "B"],
  ["What is a limiting factor?", "A factor that increases population growth", "A factor that restricts population size", "A factor that causes mutation", "A factor that increases biodiversity", "B"],
  ["What is carrying capacity?", "Maximum number of species in a biome", "Maximum population size an environment can support", "Minimum number of individuals needed for survival", "Number of predators in an ecosystem", "B"],
  ["What is competition?", "Organisms cooperating for resources", "Organisms fighting predators", "Organisms competing for limited resources", "Organisms migrating", "C"],
  ["What is predation?", "One organism eating another", "Two organisms sharing resources", "Organisms decomposing matter", "Organisms migrating", "A"],
  ["What is mutualism?", "One organism benefits, the other is harmed", "Both organisms benefit", "One benefits, the other is unaffected", "Both are harmed", "B"],
  ["What is commensalism?", "Both organisms benefit", "One benefits, the other is harmed", "One benefits, the other is unaffected", "Both are harmed", "C"],
  ["What is parasitism?", "Both organisms benefit", "One benefits, the other is harmed", "One benefits, the other is unaffected", "Both are harmed", "B"],
  ["What is ecological succession?", "Sudden extinction of species", "Gradual change in communities over time", "Migration of populations", "Mutation of organisms", "B"],
  ["What is primary succession?", "Succession in an area with soil already present", "Succession starting on bare rock with no soil", "Succession after a forest fire", "Succession in aquatic ecosystems", "B"],
  ["What is secondary succession?", "Succession starting on bare rock", "Succession in an area where soil remains after disturbance", "Succession in deserts", "Succession in oceans", "B"],
  ["What is biodiversity?", "Number of predators in an ecosystem", "Variety of life in an ecosystem", "Number of producers", "Amount of biomass", "B"],
  ["What is an invasive species?", "A native species", "A species introduced to an area that harms the ecosystem", "A species that is endangered", "A species that only eats plants", "B"],
  ["What is a keystone species?", "A species with no predators", "A species that has a disproportionately large effect on its ecosystem", "A species that migrates seasonally", "A species with a small population", "B"],
  ["What is biomagnification?", "Increase in population size", "Increase in toxin concentration at higher trophic levels", "Increase in biodiversity", "Increase in biomass", "B"],
  ["What is the greenhouse effect?", "Cooling of Earth's atmosphere", "Warming caused by trapped heat from greenhouse gases", "Increase in ozone layer thickness", "Reflection of sunlight back into space", "B"],
  ["Which gas is the main contributor to the greenhouse effect?", "Oxygen", "Nitrogen", "Carbon dioxide", "Helium", "C"],
  ["What is eutrophication?", "Increase in predators", "Excess nutrients causing algal blooms and oxygen depletion", "Increase in biodiversity", "Decrease in water temperature", "B"],
  ["What is conservation biology?", "Study of fossils", "Study of protecting biodiversity", "Study of climate only", "Study of food webs", "B"],
  ["What is sustainable development?", "Using resources without considering the future", "Using resources in a way that meets present needs without harming future generations", "Using only non-renewable resources", "Avoiding all human activity", "B"],
  ["What is ecological footprint?", "Amount of land needed to support one species", "Impact of an individual or population on the environment", "Number of organisms in a habitat", "Amount of biomass in an ecosystem", "B"],
  ["What is climate change?", "Short-term weather changes", "Long-term changes in temperature and weather patterns", "Seasonal variation", "Local rainfall differences", "B"],

  // PLANT BIOLOGY (BOTANY) — Questions 1–40
  ["What is photosynthesis?", "Breakdown of glucose", "Process by which plants make food using light", "Movement of water in plants", "Respiration in plants", "B"],
  ["Which organelle is responsible for photosynthesis?", "Mitochondrion", "Chloroplast", "Nucleus", "Ribosome", "B"],
  ["Which pigment is essential for photosynthesis?", "Hemoglobin", "Melanin", "Chlorophyll", "Keratin", "C"],
  ["What gas do plants release during photosynthesis?", "Carbon dioxide", "Oxygen", "Nitrogen", "Methane", "B"],
  ["What gas do plants absorb during photosynthesis?", "Oxygen", "Nitrogen", "Carbon dioxide", "Hydrogen", "C"],
  ["What is the main function of plant roots?", "Photosynthesis", "Absorption of water and minerals", "Gas exchange", "Seed production", "B"],
  ["What is the main function of plant stems?", "Absorb water", "Support the plant and transport substances", "Produce seeds", "Perform respiration", "B"],
  ["What is the main function of leaves?", "Reproduction", "Water storage", "Photosynthesis", "Seed dispersal", "C"],
  ["What is xylem responsible for?", "Transport of sugars", "Transport of water and minerals", "Gas exchange", "Seed formation", "B"],
  ["What is phloem responsible for?", "Transport of water", "Transport of sugars", "Transport of oxygen", "Transport of minerals", "B"],
  ["What is transpiration?", "Water absorption by roots", "Loss of water vapor from leaves", "Movement of sugars", "Seed germination", "B"],
  ["What is the stomata's function?", "Absorb minerals", "Gas exchange", "Store starch", "Produce chlorophyll", "B"],
  ["What controls the opening and closing of stomata?", "Root hairs", "Guard cells", "Xylem vessels", "Phloem tubes", "B"],
  ["What is the reproductive structure of flowering plants?", "Leaf", "Stem", "Flower", "Root", "C"],
  ["What is pollination?", "Formation of seeds", "Transfer of pollen from anther to stigma", "Growth of roots", "Transport of sugars", "B"],
  ["What is fertilization in plants?", "Transfer of pollen", "Fusion of sperm and egg cells", "Growth of the pollen tube", "Seed dispersal", "B"],
  ["What is germination?", "Formation of flowers", "Growth of a seed into a new plant", "Transfer of pollen", "Photosynthesis", "B"],
  ["Which part of the flower produces pollen?", "Stigma", "Ovary", "Anther", "Style", "C"],
  ["Which part of the flower receives pollen?", "Anther", "Stigma", "Ovule", "Sepal", "B"],
  ["What is the ovule?", "Male gamete", "Female gamete-containing structure", "Pollen grain", "Seed coat", "B"],
  ["After fertilization, the ovule becomes the:", "Fruit", "Seed", "Leaf", "Root", "B"],
  ["After fertilization, the ovary becomes the:", "Seed", "Fruit", "Stem", "Flower", "B"],
  ["What is phototropism?", "Growth in response to gravity", "Growth in response to light", "Growth in response to touch", "Growth in response to water", "B"],
  ["What is gravitropism?", "Growth in response to light", "Growth in response to gravity", "Growth in response to chemicals", "Growth in response to temperature", "B"],
  ["What is thigmotropism?", "Growth in response to touch", "Growth in response to water", "Growth in response to light", "Growth in response to gravity", "A"],
  ["What is the function of the cuticle on leaves?", "Gas exchange", "Prevent water loss", "Absorb sunlight", "Transport sugars", "B"],
  ["What are meristems?", "Regions of active cell division", "Regions of photosynthesis", "Regions of water storage", "Regions of seed formation", "A"],
  ["What is the main function of the vascular bundle?", "Gas exchange", "Transport of water and nutrients", "Seed production", "Photosynthesis", "B"],
  ["What is a monocot?", "Plant with two seed leaves", "Plant with one seed leaf", "Plant with no vascular tissue", "Plant with woody stems", "B"],
  ["What is a dicot?", "Plant with one seed leaf", "Plant with two seed leaves", "Plant with no flowers", "Plant with parallel leaf veins", "B"],
  ["What type of root system do monocots typically have?", "Taproot system", "Fibrous root system", "Adventitious root system", "Aerial root system", "B"],
  ["What type of root system do dicots typically have?", "Fibrous root system", "Taproot system", "Aerial root system", "Prop root system", "B"],
  ["What is the function of the cambium?", "Gas exchange", "Production of new xylem and phloem", "Seed formation", "Photosynthesis", "B"],
  ["What is the main function of the epidermis in plants?", "Transport of water", "Protection and prevention of water loss", "Seed production", "Sugar transport", "B"],
  ["What is the function of root hairs?", "Produce seeds", "Increase surface area for absorption", "Store starch", "Perform photosynthesis", "B"],
  ["What is a stomatal pore?", "Opening for water absorption", "Opening for gas exchange", "Opening for sugar transport", "Opening for seed release", "B"],
  ["What is the function of the palisade mesophyll?", "Gas exchange", "Water storage", "Photosynthesis", "Transport of nutrients", "C"],
  ["What is the function of the spongy mesophyll?", "Water absorption", "Gas exchange", "Seed production", "Sugar storage", "B"],
  ["What is the main function of plant hormones (phytohormones)?", "Provide energy", "Regulate growth and development", "Transport minerals", "Produce chlorophyll", "B"],
  ["Which plant hormone is responsible for cell elongation and phototropism?", "Cytokinin", "Auxin", "Ethylene", "Abscisic acid", "B"],
];

// Insert all biology questions with shuffled answers
const insertBiology = db.transaction(() => {
  shuffleAndInsert('biology', biologyQuestions);
});
insertBiology();

const chemCount = db.prepare('SELECT COUNT(*) as count FROM questions WHERE category = ?').get('chemistry').count;
const bioCount = db.prepare('SELECT COUNT(*) as count FROM questions WHERE category = ?').get('biology').count;

console.log(`Seeding complete!`);
console.log(`  Chemistry questions: ${chemCount}`);
console.log(`  Biology questions: ${bioCount}`);
console.log(`  Total: ${chemCount + bioCount}`);
